trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: CountCommits
  displayName: 'Count Commits in PR'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      git fetch --all
      SOURCE_BRANCH=$(echo $(System.PullRequest.SourceBranch) | sed 's/refs\/heads\///')
      TARGET_BRANCH=$(echo $(System.PullRequest.TargetBranch) | sed 's/refs\/heads\///')
      git checkout $TARGET_BRANCH
      git pull
      git checkout $SOURCE_BRANCH
      git pull
      git merge-base $TARGET_BRANCH $SOURCE_BRANCH
    displayName: 'Fetch and Checkout Branches'

  - script: |
      MERGE_BASE=$(git merge-base $TARGET_BRANCH $SOURCE_BRANCH)
      echo "Merge base commit: $MERGE_BASE"
      NUMBER_OF_COMMITS=$(git rev-list --count $MERGE_BASE..HEAD)
      echo "Number of commits in PR: $NUMBER_OF_COMMITS"
      echo "##vso[task.setvariable variable=numberOfCommits]$NUMBER_OF_COMMITS"
    displayName: 'Count Commits'

  - script: |
      echo "Number of commits in this PR: $(numberOfCommits)"
    displayName: 'Display Commit Count'
