trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: CountCommits
  displayName: 'Count Commits in PR'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      git fetch --all
      git checkout main
      git pull
      git checkout dev
      git pull
      git merge-base main dev
    displayName: 'Fetch and Checkout Branches'

  - script: |
      NUMBER_OF_COMMITS=$(git rev-list --count origin/$(Build.PullRequest.SourceBranchName)..origin/$(System.PullRequest.TargetBranch))
      echo "Number of commits in PR: $NUMBER_OF_COMMITS"
      echo "##vso[task.setvariable variable=numberOfCommits]$NUMBER_OF_COMMITS"
    displayName: 'Count Commits'

  - script: |
      echo "Number of commits in this PR: $(numberOfCommits)"
    displayName: 'Display Commit Count'
