trigger:
  branches:
    include:
    - main
pr:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: create_temp_environment
    displayName: Create Temp Environment
    jobs:
      - job: check_commits
        displayName: Check Commits
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - checkout: self
            fetchDepth: 0
          - task: Bash@3
            displayName: Check PR Commit Count
            inputs:
              targetType: inline
              script: |
                git fetch origin
                SOURCE_BRANCH_NAME=$(echo $(System.PullRequest.SourceBranch))
                TARGET_BRANCH_NAME=$(echo $(System.PullRequest.TargetBranch) | sed 's/refs\/heads\///')
                echo "Source branch: $SOURCE_BRANCH_NAME"
                echo "Target branch: $TARGET_BRANCH_NAME"
                commit_count=$(git rev-list --count origin/$TARGET_BRANCH_NAME..origin/$SOURCE_BRANCH_NAME)
                echo "##vso[task.setvariable variable=commitCount]$commit_count"
      - job: create_environment
        displayName: Create Environment
        dependsOn: check_commits
        condition: not(and(eq(variables['Build.Reason'], 'PullRequest'), ne(variables['commitCount'], '1')))
        steps:
          - script: |
              echo "Number of commits in the pull request: $(commitCount)"
            displayName: Print Commit Count
